#
# single machine
# 单机器多实例的redis集群
# 创建6个redis实例，3主3从
#

version: '2'
services:
  redis:
    build:
      context: .
      dockerfile: ./redis/cluster.Dockerfile
    volumes:
      - ./data/volumes/redis-cluster/redis_1:/data
    ports:
      - "7000:7000"
      - "7001:7001"
      - "7002:7002"
      - "7003:7003"
      - "7004:7004"
      - "7005:7005"


