version: '2'
services:
  web:
    build:
      context: .
      dockerfile: ./services/nginx-php/Dockerfile
      args:
        timezone: Asia/Shanghai
    container_name: ug-web
    hostname: php5-dev
    environment:
      HOSTNAME: php5-dev
    ports:
      - "2222:22"
      - "80:80"
      - "443:443"
    links:
      - mongo:mongo
      # - mysql:mysql
      - memcached:memcached
      - redis:redis
      # - elasticsearch:elasticsearch
    volumes:
      - ./www:/var/www
      - ./conf/vhosts:/etc/nginx/conf.d
      - ./logs/supervisor:/var/log/supervisor
      - ./logs/nginx:/var/log/nginx

  php7:
    build:
      context: .
      dockerfile: ./services/php/Dockerfile
      args:
        timezone: Asia/Shanghai
    container_name: ug-php7
    hostname: php7-dev
    environment:
      HOSTNAME: php7-dev
    links:
      - mongo:mongo
      # - mysql:mysql
      - redis:redis
    ports:
      - "9501:9501"
    volumes:
      - ./www:/var/www
      - ./logs/php7:/var/log/php7

  mongo:
    build:
      context: .
      dockerfile: ./services/mongo/Dockerfile
      args:
        timezone: Asia/Shanghai
    container_name: ug-mongo
    ports:
      - "27017:27017"
    volumes:
      - ./data/volumes/mongo-latest:/data/db:rw
      - ./data/volumes/mongo-latest-configdb:/data/configdb:rw

  # mysql:
  #   image: mysql:5.6
  #   container_name: ug-mysql
  #   ports:
  #     - "3306:3306"
  #   volumes:
  #     - ./data/volumes/mysql-56:/var/lib/mysql
  #   environment:
  #     MYSQL_ROOT_PASSWORD: password

  redis:
    build:
      context: .
      dockerfile: ./services/redis/Dockerfile
      args:
        timezone: Asia/Shanghai
        master_port: "6379"
        slaves_port: "6380"
    container_name: ug-redis
    volumes:
      - ./data/volumes/redis-latest:/data
      - ./conf/redis:/etc/redis
      - ./logs/redis:/var/log/redis
    ports:
      - "6379:6379"
      - "6380:6380"

  memcached:
    image: memcached
    container_name: ug-mem
    ports:
      - "11211:11211"

  gearman:
    build:
      context: .
      dockerfile: ./services/gearman/alpine.Dockerfile
    container_name: gearman
    volumes:
      - ./data/volumes/gearman-latest:/data
      - ./logs/gearmand:/var/log/gearmand
    ports:
      - "4730:4730"
