version: '3'
services:
  mysql:
    image: mysql
    container_name: dev-mysql
    ports:
      - "3306:3306"
    volumes:
      - ./data/volumes/mysql-latest:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password

  memcached:
    image: memcached
    container_name: dev-mem
    ports:
      - "11211:11211"

  redis:
    extends:
      file: ./compose.common-v2.yml
      service: redis
    container_name: dev-redis
    ports:
      - "6379:6379"
      - "6380:6380"

  # gearman:
  #   extends:
  #     file: ./compose.common-v2.yml
  #     service: gearman
  #   container_name: dev-gearman
  #   ports:
  #      - "4730:4730"

  # elasticsearch:
  #   image: elasticsearch
  #   container_name: dev-es
  #   volumes:
  #     - ./data/volumes/es-latest:/usr/share/elasticsearch/data
  #   ports:
  #     - "9200:9200"
  #     - "9300:9300"

  nginx:
    extends:
      file: ./compose.common-v2.yml
      service: nginx
    container_name: dev-nginx
    links:
      - php5:php5
      - php7:php7
    volumes:
      # custom difine the www directory.
      - www-data:/var/www
      - ./conf/vhosts:/etc/nginx/conf.d
      - ./logs/nginx:/var/log/nginx

  php5:
    extends:
      file: ./compose.common-v2.yml
      service: php5
    container_name: dev-php5
    links:
      # - mysql:mysql
      # - mongo:mongo
      - redis:redis
      - memcached:memcached
      # - gearman:gearman
      # - elasticsearch:elasticsearch
    volumes:
      # custom difine the www directory.
      - www-data:/var/www

  php7:
    extends:
      file: ./compose.common-v2.yml
      service: php7
    container_name: dev-php7
    links:
      # - mysql:mysql
      # - mongo:mongo
      - redis:redis
      - memcached:memcached
      # - gearman:gearman
      # - elasticsearch:elasticsearch
    volumes:
      # custom difine the www directory.
      - www-data:/var/www

