web:
  build: ./docker
  ports:
    - "80:80"
    - "443:443"
    - "9000:9000"
  links:
    - mysql:mysql
    - memcached:memcached
    - redis:redis
    - elasticsearch:elasticsearch
  volumes:
    - /Users/inhere/Workspace/php:/var/www
    - ./sites:/etc/nginx/conf.d
    - ./logs/supervisor:/var/log/supervisor
    - ./logs/nginx:/var/log/nginx

mysql:
  image: mysql
  ports:
    - "3306:3306"
  environment:
    MYSQL_ROOT_PASSWORD: password

memcached:
  image: memcached
  ports:
    - "11211:11211"

redis:
  image: redis
  ports:
    - "6379:6379"

elasticsearch:
  image: elasticsearch
  ports:
    - "9200:9200"
    - "9300:9300"

