version: '2'
services:
  mysql:
    image: mysql
    container_name: dev-mysql
    ports:
      - "3306:3306"
    volumes:
      - ./data/volumes/mysql-latest:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password

  mongo:
    image: mongo
    container_name: dev-mongo
    ports:
      - "27017:27017"
    volumes:
      - ./data/volumes/mongo-latest:/data/db
      - ./data/volumes/mongo-latest-configdb:/data/configdb

  memcached:
    image: memcached
    container_name: dev-mem
    ports:
      - "11211:11211"

  redis:
    build:
      # define the context dir, copy and move file will reference it on the Dockerfile.
      context: .
      dockerfile: ./services/redis/single.Dockerfile
      args:
        timezone: Asia/Shanghai
    container_name: dev-redis
    ports:
      - "6379:6379"

  # elasticsearch:
  #   image: elasticsearch
  #   container_name: dev-es
  #   volumes:
  #     - ./data/volumes/es-latest:/usr/share/elasticsearch/data
  #   ports:
  #     - "9200:9200"
  #     - "9300:9300"

  nginx:
    build:
      context: .
      dockerfile: ./services/nginx/Dockerfile
      args:
        timezone: Asia/Shanghai
    container_name: dev-nginx
    ports:
      - "80:80"
      - "443:443"
    links:
      - php:php
    volumes:
      # custom difine the www directory.
      - ./www:/var/www
      - ./conf/vhosts:/etc/nginx/conf.d
      - ./logs/nginx:/var/log/nginx

  php:
    build:
      context: .
      dockerfile: ./services/php/Dockerfile
      args:
        timezone: Asia/Shanghai
    container_name: dev-php
    hostname: php-dev
    links:
      - mysql:mysql
      - mongo:mongo
      - redis:redis
      - memcached:memcached
      # - elasticsearch:elasticsearch
    ports:
      - "9000:9000"
      - "9501:9501"
    volumes:
      # custom difine the www directory.
      - ./www:/var/www


