FROM nginx

MAINTAINER inhere<cloud798@126.com>

################################################################################
# Volumes
################################################################################

VOLUME ["/var/www", "/etc/nginx/conf.d"]

# extend form parent image
# EXPOSE 80 443
# CMD ["nginx", "-g", "daemon off;"]